CREATE TABLE CUSTOMERS (

  CUSTOMER_ID: BIGINT PRIMARY KEY AUTO_INCREMENT,
  NOM: VARCHAR(64),
  PRENOM: VARCHAR(85),
  EMAIL : VARCHAR(128) UNIQUE,
  TELEPHONE: VARCHAR(32),
  VILLE: VARCHAR(64),
  QUARTIER: VARCHAR(64)
  LOCALISATION: VARCHAR5(150000)
);


CREATE TABLE ORDERS(
    ORDER_ID: VARCHAR(16) PRIMARY KEY,
    CUSTOMER_ID : BIGINT,
    SALESPERSON_ID: BIGINT,
);